### ISSUE TITLE
Feature request: Can tab names be added to side nav?

### ISSUE THREAD

**Issue by christopherpickering** [pradyunsg/sphinx-inline-tabs#12]
Hi,
Is it possible to add tabs to sidebar nav of the page?

Tabs are basically replacing two section headings, and in a long page its nice to have the tab heading present in the side bar to scroll down to it on click.

![image](https://user-images.githubusercontent.com/17788706/111686257-d6c6f600-87f6-11eb-9f7e-eb7b40e89cc7.png)

Thanks!

**Comment by pradyunsg** [comment]
Oooooo. That's an interesting idea.

**Comment by pradyunsg** [comment]
Thinking about this a bunch more, this is actually a neat idea but a _LOT_ of complexity to actually make happen. This would need to some way to hack into Sphinx's ToC, and some additional complexity/logic to figure out what the right place and nodes to add to it are (should it be all the nodes, what about tabs that show up in various sections, what about tabs that don't, what if you wanna hide a node or two etc).

Overall, while I do think this would be cool; I'd consider it out of scope for this specific project, since one of the goals with this project is to keep things simple and small.

I'd suggest taking this up as an enhancement over on https://github.com/executablebooks/sphinx-tabs/ -- that tries to be significantly wider in its support umbrella, and this sort of complexity might be a better fit there.

All that said, hey, thanks for filing an issue with an interesting idea! ^>^

**Comment by christopherpickering** [comment]
thanks! but to get in the sidebar you just need a special tag, right? Can we do a tag w/ visibility=none to get the link created?

**Comment by christopherpickering** [comment]
Thanks for the link as well.. their tabs do not look nearly as cool as yours 😢

**Comment by pradyunsg** [comment]
If it were that simple, I'd have happily added this! :P

This would likely need to fiddle with Sphinx's "page content" hierarchy, which is very difficult to get to without modifying docutils internals -- something that... IDEK where to begin to explore how to do this. And all of this would be extremely fragile and a generally a big pain to maintain.

**Comment by pradyunsg** [comment]
There's also sphinx-panels: https://sphinx-panels.readthedocs.io/en/latest/ -- which has tabs that look good within Furo too! :)

**Comment by pradyunsg** [comment]
Closing as non-actionable, since I don't want this extension to fiddle with anything external to it.
