### ISSUE TITLE
Allow use on Python 3.6

### ISSUE THREAD

**Issue by tomwatson1024** [pradyunsg/sphinx-inline-tabs#24]
`pyproject.toml` defines the minimum Python version as 3.8. Installing on 3.6 seems to work fine, however.

As someone who's stuck on 3.6 it'd be great if this constraint could be relaxed. I'd understand if you want to keep the possibility of 3.8 features open, though.

**Comment by astrojuanlu** [comment]
This line gives an error on Python 3.6:

https://github.com/pradyunsg/sphinx-inline-tabs/blob/36c8c30fc772472812b1da254b2bebf3c5502083/src/sphinx_inline_tabs/_impl.py#L4

```
$ python3.6
Python 3.6.15 (default, Sep 10 2021, 00:26:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Literal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Literal'
```

So sphinx-inline-tabs is not compatible with Python 3.6 at the moment.

**Comment by tomwatson1024** [comment]
Ah, that's a shame. This particular error could be mitigated by importing `Literal` from `typing_extensions` instead, but I understand this might not be a road you want to go down!

**Comment by pradyunsg** [comment]
Yea, 3.6 goes EOL in about two weeks.

And I think pushing documentation builds forward to newer Python versions should be not problematic in general -- there's significantly smaller dependency graphs and less strict revenue-generating requirements on these in most spaces (open source, $corp etc). if it is somehow stuck, I think the fix for that is an organisational one, not something that requires me to do additional work. :)
